### ISSUE TITLE
Feature Request: Easy Open blank query tab

### ISSUE THREAD

**Issue by CharlieF107** [TablePlus/TablePlus-Windows#45]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.5.14 - Windows 10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
56

3. The steps to reproduce this issue:
I searched and saw that @bladefist opened a request #14 on Oct 12, 2018 that is very much like this, but I have a similar need.
When I click the square SQL button to open a new tab, any previous queries are present, a feature I guess. Fine.
But I often try to write new queries on the fly. and to do so, I want a new clean window. To get one, I must select-all and delete the contents of the window -- not difficult but annoying. I wish there was a simple way to open a new blank tab! How about a right-click on the SQL button with a "New Tab" option with nothing remembered in it?

Also, sometimes I work across multiple tabs, and might have 6 or 8 open, and it would be really helpful if I could drag tabs to new locations just like browsers do. Navigation would be much enhanced!

Thanks for considering these.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by bladefist** [comment]
I've come to love the feature of it remembering my old queries.  But, as you have stated, sometimes you want a fresh page fast.  So I'm in support of this as well.

**Comment by huyphams** [comment]
Thanks @CharlieF107 and @bladefist for the suggestion, I will find the way to improve it, right click on SQL button could be is a great idea!

**Comment by rwhirn** [comment]
I also notice that you open another SQL query window and you get a different historical query. Also nice. If I keep opening query tabs I keep getting older queries until it runs out. How much history does it keep? I find myself open multiple query tabs until I find the one I want. Maybe there should be a "history" tab where you can see and select which historical query you want, otherwise you have just a blank fresh query as requested above.

**Comment by joe-gall** [comment]
I see this issue is a few years old at this point so not sure if it ever will be completed. I agree with @CharlieF107 and @bladefist -- having a way to get an empty window would be amazing.  It's so annoying to have to clear out contents from a query I wrote last week.

**Comment by huyphams** [comment]
You can turn off this feature by unchecking this. I'm sorry for not answering and closing the issue sooner. 
<img width="426" alt="CleanShot 2023-01-18 at 20 32 25@2x" src="https://user-images.githubusercontent.com/3654622/213184634-a6815e4e-115a-4c5a-aac6-15b1acd79f7e.png">

**Comment by rwhirn** [comment]
@huyphams I'm not sure this is exactly "answers" the request. What this does is say "you can either have recent queries or not" it doesn't give you the ability to quickly open a blank tab. Its an "either or". 

This also applies to my issue #537 because inexplicably double clicking a History query opens up appended to the most recent query. So again, I can "fix" that error by not having any recent queries. But I'd really rather have both.
