### ISSUE TITLE
Restore window BUG

### ISSUE THREAD

**Issue by bewareilive** [TablePlus/TablePlus-Windows#512]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): postgres14

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):486

3. The steps to reproduce this issue:

1   Can table comments be displayed in table structure and info SQL?It would be better if it could also be displayed in the list.
2   When can we use Clickhouse connection like mac ?
3   I submitted a bug , and several versions still haven't been solved:
       Maximize the window to full screen----click "menu"------Click on the blank area at the top-----The window will be restored

**Comment by son11592** [comment]
Hi @bewareilive, sorry for late response. Here is our answers about your feedbacks.

> 1 Can table comments be displayed in table structure and info SQL?It would be better if it could also be displayed in the list.

The `Table Comment` are available in the `Item Overview` tab _(you can open it by right-clicking on any items in the left side bar)_. At here, you are able to make any changes on this.

> Can table comments be displayed in table structure

Currently, we don't have any plans to do it. Sorry for this inconvenience.

> and info SQL

Of course, the next update will contain it.

> When can we use Clickhouse connection like mac ?

ClickHouse database is under developement, we will bring it to Windows version soon.

> Maximize the window to full screen----click "menu"------Click on the blank area at the top-----The window will be restored

This issue is weird, I had faced it but I have no idea to deal with it. Maybe it's an issue of Windows dialog. Anw, we will try to fix it ASAP.

Thank you for your feedbacks,
Son.

**Comment by bewareilive** [comment]
> Hi @bewareilive, sorry for late response. Here is our answers about your feedbacks.
> 
> > 1 Can table comments be displayed in table structure and info SQL?It would be better if it could also be displayed in the list.
> 
> The `Table Comment` are available in the `Item Overview` tab _(you can open it by right-clicking on any items in the left side bar)_. At here, you are able to make any changes on this.
> 
> > Can table comments be displayed in table structure
> 
> Currently, we don't have any plans to do it. Sorry for this inconvenience.
> 
> > and info SQL
> 
> Of course, the next update will contain it.
> 
> > When can we use Clickhouse connection like mac ?
> 
> ClickHouse database is under developement, we will bring it to Windows version soon.
> 
> > Maximize the window to full screen----click "menu"------Click on the blank area at the top-----The window will be restored
> 
> This issue is weird, I had faced it but I have no idea to deal with it. Maybe it's an issue of Windows dialog. Anw, we will try to fix it ASAP.
> 
> Thank you for your feedbacks, Son.

Item Overview! I didn't even know until right now.  
I think this can be open it when click Table button. This is easier to find and simpler to use.

Thank you for your answer
